FROM python:3.10-slim
WORKDIR /app/service

# Added 'uvicorn' to the end of the installation list
RUN pip install --no-cache-dir fastapi mysql-connector-python matplotlib uvicorn websockets httpx

# Copy the backend source
COPY service/ .
EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
