FROM python:3.10-slim
WORKDIR /app/service

RUN pip install --no-cache-dir fastapi mysql-connector-python matplotlib

# Copy the backend source
COPY service/ .

EXPOSE 5000
CMD ["python3", "main.py"]
