import React, { useState } from 'react';

function Research() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [selectedGame, setSelectedGame] = useState(null);

  // Mock Data for Research Dashboard
  const games = [
    { id: 1, date: '2025-04-10', rounds: 45, survivors: 2, resource_total: 500 },
    { id: 2, date: '2025-04-11', rounds: 12, survivors: 0, resource_total: 120 },
    { id: 3, date: '2025-04-12', rounds: 88, survivors: 8, resource_total: 1200 },
  ];

  const handleLogin = (e) => {
    e.preventDefault();
    // In reality: POST /api/research/login
    setIsLoggedIn(true);
  };

  // --- View 1: Login ---
  if (!isLoggedIn) {
    return (
      <div className="card" style={{ maxWidth: '400px', margin: '50px auto' }}>
        <h2 style={{ textAlign: 'center' }}>Research Access</h2>
        <form onSubmit={handleLogin}>
          <label>Email</label>
          <input type="email" placeholder="researcher@lab.edu" required />

          <label>Password</label>
          <input type="password" required />

          <button type="submit" className="btn" style={{ width: '100%', marginTop: '10px' }}>
            Login
          </button>
        </form>
      </div>
    );
  }

  // --- View 2: Dashboard ---
  return (
    <div>
      <h1>Research Dashboard</h1>
      <div style={{ display: 'flex', gap: '20px' }}>

        {/* Game List */}
        <div className="card" style={{ flex: 1 }}>
          <h3>Game Logs</h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid #ddd', textAlign: 'left' }}>
                <th>ID</th>
                <th>Date</th>
                <th>Rounds</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {games.map(g => (
                <tr key={g.id} style={{ borderBottom: '1px solid #eee' }}>
                  <td style={{ padding: '10px 0' }}>{g.id}</td>
                  <td>{g.date}</td>
                  <td>{g.rounds}</td>
                  <td>
                    <button
                      className="btn btn-secondary"
                      style={{ padding: '5px 10px', fontSize: '0.8rem' }}
                      onClick={() => setSelectedGame(g)}
                    >
                      Analyze
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Visualization Area */}
        <div className="card" style={{ flex: 2 }}>
          {selectedGame ? (
            <div>
              <h3>Visualizations: Game #{selectedGame.id}</h3>
              <p>Total Resources Generated: {selectedGame.resource_total}</p>

              <div style={{ marginTop: '30px', textAlign: 'center' }}>
                {/* DATA VISUALIZATION STRATEGY:
                  
                  Since you want to use Matplotlib/Seaborn (Python), you have two options:

                  OPTION 1 (Static Images - Easiest):
                  Have your Flask endpoint return a base64 encoded string of the plot.
                  Example: 
                  <img src={`data:image/png;base64,${base64StringFromApi}`} />

                  OPTION 2 (Interactive - React Way):
                  Send the raw data (JSON) to the frontend and use a library like 
                  'recharts' or 'victory'.
                  
                  Below is a simulation of Option 1 (The Image approach):
                */}
                <div style={{
                  width: '100%',
                  height: '300px',
                  backgroundColor: '#f9f9f9',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1px dashed #ccc'
                }}>
                  [Matplotlib Graph generated by Python Backend would appear here]
                  <br />
                  (e.g., Sentiment vs. Wealth Correlation)
                </div>
              </div>
            </div>
          ) : (
            <p style={{ color: '#888', fontStyle: 'italic' }}>Select a game to view visualizations.</p>
          )}
        </div>

      </div>
    </div>
  );
}

export default Research;
