import React, { useEffect, useState } from 'react';
import { ResearchPresenter, ResearchView } from '../presenters/ResearchPresenter';

interface ResearchGame {
  id: number;
  date: string;
  rounds: number;
  survivors: number;
  resource_total: number;
}

const Research: React.FC = () => {
  const [presenter, setPresenter] = useState<ResearchPresenter | null>(null);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [selectedGame, setSelectedGame] = useState<ResearchGame | null>(null);
  const [games, setGames] = useState<ResearchGame[]>([]);

  useEffect(() => {
    const view: ResearchView = {
      setIsLoggedIn,
      setSelectedGame,
      setGames,
    };
    const researchPresenter = new ResearchPresenter(view);
    setPresenter(researchPresenter);
  }, []);

  if (!presenter) {
    return <div>Loading...</div>;
  }

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    presenter.handleLogin();
  };

  if (!isLoggedIn) {
    return (
      <div className="card" style={{ maxWidth: '400px', margin: '50px auto' }}>
        <h2 style={{ textAlign: 'center' }}>Research Access</h2>
        <form onSubmit={handleLogin}>
          <label>Email</label>
          <input type="email" placeholder="researcher@lab.edu" required />

          <label>Password</label>
          <input type="password" required />

          <button type="submit" className="btn" style={{ width: '100%', marginTop: '10px' }}>
            Login
          </button>
        </form>
      </div>
    );
  }

  return (
    <div>
      <h1>Research Dashboard</h1>
      <div style={{ display: 'flex', gap: '20px' }}>

        <div className="card" style={{ flex: 1 }}>
          <h3>Game Logs</h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid #ddd', textAlign: 'left' }}>
                <th>ID</th>
                <th>Date</th>
                <th>Rounds</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {games.map(g => (
                <tr key={g.id} style={{ borderBottom: '1px solid #eee' }}>
                  <td style={{ padding: '10px 0' }}>{g.id}</td>
                  <td>{g.date}</td>
                  <td>{g.rounds}</td>
                  <td>
                    <button
                      className="btn btn-secondary"
                      style={{ padding: '5px 10px', fontSize: '0.8rem' }}
                      onClick={() => presenter.handleSelectGame(g)}
                    >
                      Analyze
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="card" style={{ flex: 2 }}>
          {selectedGame ? (
            <div>
              <h3>Visualizations: Game #{selectedGame.id}</h3>
              <p>Total Resources Generated: {selectedGame.resource_total}</p>

              <div style={{ marginTop: '30px', textAlign: 'center' }}>
                <div style={{
                  width: '100%',
                  height: '300px',
                  backgroundColor: '#f9f9f9',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1px dashed #ccc'
                }}>
                  [Matplotlib Graph generated by Python Backend would appear here]
                  <br />
                  (e.g., Sentiment vs. Wealth Correlation)
                </div>
              </div>
            </div>
          ) : (
            <p style={{ color: '#888', fontStyle: 'italic' }}>Select a game to view visualizations.</p>
          )}
        </div>

      </div>
    </div>
  );
}

export default Research;
